# Generated by Django 4.2.4 on 2023-10-31 00:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComunidadMiembros',
            fields=[
                ('comunidad', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='mainApp.comunidad')),
                ('rol_comunidad', models.CharField(blank=True, max_length=255, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'comunidad_miembros',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Entidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('localidad', models.CharField(blank=True, max_length=255, null=True)),
                ('municipio', models.CharField(blank=True, max_length=255, null=True)),
                ('provincia', models.CharField(blank=True, max_length=255, null=True)),
                ('nombre', models.CharField(blank=True, max_length=255, null=True)),
                ('tipoentidad', models.CharField(blank=True, db_column='tipoEntidad', max_length=255, null=True)),
            ],
            options={
                'db_table': 'entidad',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Entidadprestadora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criterio', models.CharField(blank=True, max_length=35, null=True)),
                ('nombre', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'entidadprestadora',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EstablecimientoServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'establecimiento_servicio',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MiembroEntidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'miembro_entidad',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Organismodecontrol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'organismodecontrol',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ServiciosMiembro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serviciosasociados', models.CharField(blank=True, db_column='serviciosAsociados', max_length=255, null=True, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'servicios_miembro',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TiposerviciosOrganismodecontrol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servicioacontrolar', models.CharField(blank=True, db_column='servicioAControlar', max_length=255, null=True, unique=True)),
            ],
            options={
                'db_table': 'tiposervicios_organismodecontrol',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apellido', models.CharField(blank=True, max_length=255, null=True)),
                ('contrasenia', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('nombre', models.CharField(blank=True, max_length=255, null=True)),
                ('nombreusuario', models.CharField(blank=True, db_column='nombreUsuario', max_length=255, null=True)),
                ('rolusuario', models.CharField(blank=True, db_column='rolUsuario', max_length=255, null=True)),
            ],
            options={
                'db_table': 'usuario',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='comunidad',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='establecimiento',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='incidente',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='miembro',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='servicio',
            options={'managed': False},
        ),
    ]
